#!/usr/bin/env python3
"""
Regenerates drafts/motion/index.html from the pattern page.

WHY A SCRIPT RATHER THAN A COPY. A hand-made copy drifts the first time
the pattern page changes, and then the sampler is showing motion over
copy nobody is shipping. This regenerates it, so the answer to "is the
sampler current" is `python3 drafts/motion/build.py --check`.

WHAT IT CHANGES, and it is deliberately almost nothing:

  1. Asset paths, ../assets/ -> ../../docs/assets/, and the ?v= stamps
     come off. drafts/ is not stamped by scripts/stamp-assets.py, so a
     stamp copied in here could only ever go stale.
  2. Two extra files, motion.css and motion.js, loaded AFTER the
     production pair so the diff to adopt anything is obvious.
  3. The sampler bar, and a title that says what this is.

EVERYTHING ELSE THE SAMPLER DOES IS DONE AT RUNTIME BY motion.js. No
odometer markup, no stamp markup, no lane markup lives in this file,
because the point is to show what the effects cost on the REAL page,
not on a page rebuilt to suit them.

    python3 drafts/motion/build.py            # write index.html
    python3 drafts/motion/build.py --check    # exit 1 if it is stale
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(ROOT, "docs", "collision-repair", "index.html")
OUT = os.path.join(HERE, "index.html")

BAR = '''
<!-- ===================== THE SAMPLER BAR =====================
     Not a candidate effect. It is the furniture for judging them: a
     replay, because every entrance here runs ONCE and you would
     otherwise reload to see it twice, and a switch that forces the
     reduced-motion path so the hard rule can be checked without going
     into System Settings. Neither ships. -->
<div class="mo-bar" role="region" aria-label="Motion sampler controls">
  <strong>MOTION SAMPLER</strong>
  <span class="mo-bar-list">
    <a href="#process">D lane, undecided</a><a href="#faq">E accordion, undecided</a>
    <span>C lift: ADOPTED, ships from site.css, hover any card</span>
  </span>
  <button type="button" class="mo-replay">Replay entrances</button>
  <label class="mo-reduce"><input type="checkbox"> Force reduced motion</label>
  <span class="mo-state" aria-live="polite"></span>
</div>
'''


def build() -> str:
    with open(SOURCE, encoding="utf-8") as f:
        html = f.read()

    # 1. assets, and drop the cache-busting stamps
    html = html.replace('href="../assets/', 'href="../../docs/assets/')
    html = html.replace('src="../assets/', 'src="../../docs/assets/')
    html = html.replace('src="../logo.png"', 'src="../../docs/logo.png"')
    html = re.sub(r'(\.(?:css|js))\?v=[0-9a-f]+"', r'\1"', html)

    # 2. the sampler's own two files, after the production pair
    html = html.replace(
        '<link rel="stylesheet" href="../../docs/assets/site.css">',
        '<link rel="stylesheet" href="../../docs/assets/site.css">\n'
        '  <link rel="stylesheet" href="motion.css">', 1)
    html = re.sub(r'(<script src="\.\./\.\./docs/assets/site\.js"[^>]*></script>)',
                  r'\1\n<script src="motion.js" defer></script>', html, count=1)

    # 3. say what it is, in the title and on the page
    html = re.sub(r"<title>.*?</title>",
                  "<title>MOTION SAMPLER: Collision Repair | Tri-County Collision</title>",
                  html, count=1, flags=re.S)
    html = html.replace("<body>", "<body>" + BAR, 1)

    header = ("<!-- GENERATED BY drafts/motion/build.py. DO NOT EDIT BY HAND.\n"
              "     Source: docs/collision-repair/index.html\n"
              "     Every candidate effect is applied at runtime by motion.js.\n"
              "     Read drafts/motion/README.md before judging any of it. -->\n")
    return header + html


def main() -> int:
    fresh = build()
    if "--check" in sys.argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            print("drafts/motion/index.html is missing.", file=sys.stderr)
            return 1
        if current != fresh:
            print("drafts/motion/index.html is stale. Run drafts/motion/build.py.",
                  file=sys.stderr)
            return 1
        print("drafts/motion/index.html is current.")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(fresh)
    print(f"Wrote {os.path.relpath(OUT, ROOT)} from the pattern page.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
